# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20161116_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='concelho',
            name='distrito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freguesia',
            name='concelho',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Concelho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='concelho',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Concelho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='distrito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='freguesia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Freguesia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='us',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Tipo'),
            preserve_default=False,
        ),
    ]
