# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20161117_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='concelho',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='freguesia',
        ),
        migrations.AddField(
            model_name='us',
            name='freguesia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Freguesia'),
            preserve_default=False,
        ),
    ]
