# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20161121_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoSintomas',
            new_name='Grupo_Sintomas',
        ),
        migrations.RenameModel(
            old_name='OpcoesSintomas',
            new_name='Opcoes_Sintomas',
        ),
        migrations.RenameModel(
            old_name='SeleccaoSintomas',
            new_name='Seleccao_Sintomas',
        ),
    ]
