# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20161121_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo_Sintomas',
            new_name='Gruposintomas',
        ),
        migrations.RenameModel(
            old_name='Opcoes_Sintomas',
            new_name='Opcoessintomas',
        ),
        migrations.RenameModel(
            old_name='Seleccao_Sintomas',
            new_name='Seleccaosintomas',
        ),
    ]
