# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_auto_20161121_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opcoessintomas',
            new_name='Opcoesintomas',
        ),
    ]
